### ISSUE TITLE
White Screen after login in on iOS devices (iPhone & iPad)

### ISSUE THREAD

**Issue by Rymblock** [cockpit-project/cockpit#10146]
Good Afternoon.

New in github , so I do apologize if this issue was already open and I did not find it. 

I have a working cockpit server working over Debian 9 (stable), fully functional when you access from a laptop/desk but with no access from an iPad Pro 10.5.

Screen is just white after the logging window. Tried with every single brower in the app market with no different results.

After few days researching/googling around, cant see how to fix it.

Thanks. Please make me know any defaults you may require.

**Comment by leomoty** [comment]
It just shows a white screen on my Ipad Mini 2 as well after logging in.

Regarding other apps, I doubt it would matter, if you check section 2.5.6:

https://developer.apple.com/app-store/review/guidelines/#software-requirements

In practice, they all share WebKit as rendering engine, so they should share the same issues.

**Comment by martinpitt** [comment]
Can you get a JavaScript console there and check for any error messages?

@larskarlitski , @garrett , is this by chance reproducible on your Apple laptop?

**Comment by leomoty** [comment]
Hey @martinpitt, I asked a friend to test. He tested both with 172 locally (his own server) and with 178 (my server).

- Cockpit 172 works fine
- Cockpit 178 shows an empty screen and fails with the errors below:

<pre>
[Error] Failed to load resource: the server responded with a status of 401 (Authentication failed) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (login.min.js.map, line 0)
[Error] WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.) (x2)
[Error] received unsupported version in init message: undefined
    E (cockpit.js:393)
    S (cockpit.js:416)
    dispatch_data (cockpit.js:365)
    t (cockpit.js:226)
[Error] received message before init:  – “hint”
    S (cockpit.js:420)
    dispatch_data (cockpit.js:365)
    t (cockpit.js:226)
</pre>

<details>
<summary>More Websocket Errors (click to expand)</summary>
<pre>
[Error] WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.) (x2)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"internal\",\"payload\":\"dbus-json3\",\"command\":\"open\",\"channel\":\"1\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "1↵{\"add-match\":{\"path\":\"/machines\",\"interface\":\"cockpit.Machines\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "1↵{\"watch\":{\"path\":\"/machines\",\"interface\":\"cockpit.Machines\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "1↵{\"type\":\"s\",\"call\":[\"/user\",\"org.freedesktop.DBus.Properties\",\"GetAll\",[\"cockpit.User\"]],\"id\":\"3\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"command\":\"authorize\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"null\",\"command\":\"open\",\"channel\":\"2\",\"flow-control\":true}" (cockpit.js, line 442)
[Warning] transport closed: disconnected (index.js, line 3621)
[Log] transport closed, dropped message:  – "↵{ \"command\": \"init\", \"version\": 1 }" (cockpit.js, line 442)
[Error] received unsupported version in init message: undefined
	E (cockpit.js:393)
	S (cockpit.js:416)
	dispatch_data (cockpit.js:365)
	t (cockpit.js:226)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"internal\",\"payload\":\"dbus-json3\",\"command\":\"open\",\"channel\":\"1\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "1↵{\"type\":\"s\",\"call\":[\"/user\",\"org.freedesktop.DBus.Properties\",\"GetAll\",[\"cockpit.User\"]],\"id\":\"1\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"null\",\"superuser\":\"require\",\"command\":\"open\",\"channel\":\"2\",\"flow-control\":true}" (cockpit.js, line 442)
[Error] received message before init:  – "hint"
	S (cockpit.js:420)
	dispatch_data (cockpit.js:365)
	t (cockpit.js:226)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"internal\",\"payload\":\"dbus-json3\",\"command\":\"open\",\"channel\":\"3\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "3↵{\"type\":\"s\",\"call\":[\"/user\",\"org.freedesktop.DBus.Properties\",\"GetAll\",[\"cockpit.User\"]],\"id\":\"1\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"null\",\"superuser\":\"require\",\"command\":\"open\",\"channel\":\"4\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"fswatch1\",\"path\":\"/etc/motd\",\"command\":\"open\",\"channel\":\"5\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"fsread1\",\"path\":\"/etc/motd\",\"command\":\"open\",\"channel\":\"6\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"system\",\"payload\":\"dbus-json3\",\"name\":\"org.freedesktop.timedate1\",\"command\":\"open\",\"channel\":\"7\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"add-match\":{\"path\":\"/org/freedesktop/timedate1\",\"interface\":\"org.freedesktop.timedate1\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"watch\":{\"path\":\"/org/freedesktop/timedate1\",\"interface\":\"org.freedesktop.timedate1\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"superuser\":\"try\",\"payload\":\"dbus-json3\",\"name\":\"org.freedesktop.systemd1\",\"command\":\"open\",\"channel\":\"8\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "8↵{\"add-match\":{\"path\":\"/org/freedesktop/systemd1\",\"interface\":\"org.freedesktop.systemd1.Manager\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "8↵{\"watch\":{\"path\":\"/org/freedesktop/systemd1\",\"interface\":\"org.freedesktop.systemd1.Manager\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"stream\",\"spawn\":[\"date\",\"+%s:%:z\"],\"err\":\"message\",\"command\":\"open\",\"channel\":\"9\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"superuser\":\"try\",\"payload\":\"dbus-json3\",\"name\":\"org.freedesktop.PackageKit\",\"command\":\"open\",\"channel\":\"10\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "10↵{\"call\":[\"/org/freedesktop/PackageKit\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.PackageKit\",\"VersionMajor\"]],\"id\":\"1\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "10↵{\"call\":[\"/org/freedesktop/PackageKit\",\"org.freedesktop.PackageKit\",\"CreateTransaction\",[]],\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"system\",\"payload\":\"dbus-json3\",\"name\":\"com.redhat.SubscriptionManager\",\"command\":\"open\",\"channel\":\"11\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "11↵{\"add-match\":{\"path\":\"/EntitlementStatus\",\"interface\":\"com.redhat.SubscriptionManager.EntitlementStatus\",\"member\":\"entitlement_status_cha…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "11↵{\"call\":[\"/EntitlementStatus\",\"com.redhat.SubscriptionManager.EntitlementStatus\",\"check_status\",[]],\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"fsread1\",\"path\":\"/etc/machine-id\",\"command\":\"open\",\"channel\":\"12\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"superuser\":true,\"payload\":\"dbus-json3\",\"name\":\"org.projectatomic.rpmostree1\",\"command\":\"open\",\"channel\":\"13\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "13↵{\"add-match\":{\"path\":\"/org/projectatomic/rpmostree1/Sysroot\",\"interface\":\"org.projectatomic.rpmostree1.Sysroot\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "13↵{\"watch\":{\"path\":\"/org/projectatomic/rpmostree1/Sysroot\",\"interface\":\"org.projectatomic.rpmostree1.Sysroot\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"superuser\":\"try\",\"payload\":\"dbus-json3\",\"name\":\"org.freedesktop.hostname1\",\"command\":\"open\",\"channel\":\"14\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "14↵{\"add-match\":{\"path\":\"/org/freedesktop/hostname1\",\"interface\":\"org.freedesktop.hostname1\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "14↵{\"watch\":{\"path\":\"/org/freedesktop/hostname1\",\"interface\":\"org.freedesktop.hostname1\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"pcp-archive\",\"metrics\":[{\"name\":\"mem.util.used\",\"units\":\"bytes\"}],\"timestamp\":-300470,\"limi…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"pcp-archive\",\"metrics\":[{\"name\":\"network.interface.total.bytes\",\"units\":\"bytes\",\"derive\":\"r…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"pcp-archive\",\"metrics\":[{\"name\":\"disk.all.total_bytes\",\"units\":\"bytes\",\"derive\":\"rate\"}],\"t…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"stream\",\"spawn\":[\"cat\",\"/proc/meminfo\",\"/proc/cpuinfo\"],\"command\":\"open\",\"channel\":\"18\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"stream\",\"spawn\":[\"grep\",\"-r\",\".\"],\"directory\":\"/sys/class/dmi/id\",\"err\":\"ignore\",\"superuser\":\"try\",\"command\":\"open\",\"channel\":\"…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"stream\",\"spawn\":[\"hostname\"],\"err\":\"ignore\",\"command\":\"open\",\"channel\":\"20\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"bus\":\"system\",\"payload\":\"dbus-json3\",\"name\":\"org.freedesktop.realmd\",\"command\":\"open\",\"channel\":\"21\",\"flow-control\":true}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "21↵{\"watch\":{\"path\":\"/org/freedesktop/realmd\"},\"id\":\"1\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "21↵{\"add-match\":{\"interface\":\"org.freedesktop.realmd.Realm\",\"path_namespace\":\"/\"}}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "21↵{\"watch\":{\"interface\":\"org.freedesktop.realmd.Realm\",\"path_namespace\":\"/\"},\"id\":\"2\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"direct\",\"metrics\":[{\"name\":\"mem.util.used\",\"units\":\"bytes\"}],\"command\":\"open\",\"channel\":\"22…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"direct\",\"metrics\":[{\"name\":\"disk.all.total_bytes\",\"units\":\"bytes\",\"derive\":\"rate\"}],\"comman…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "↵{\"payload\":\"metrics1\",\"interval\":1000,\"source\":\"direct\",\"metrics\":[{\"name\":\"network.interface.total.bytes\",\"units\":\"bytes\",\"derive\":\"rate\"}…" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"3\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"4\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"5\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"6\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"7\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"8\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"9\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"10\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"11\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"12\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"13\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"14\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"15\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"16\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"17\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"18\"}" (cockpit.js, line 442)
[Log] transport closed, dropped message:  – "7↵{\"call\":[\"/org/freedesktop/timedate1\",\"org.freedesktop.DBus.Properties\",\"Get\",[\"org.freedesktop.timedate1\",\"NTPSynchronized\"]],\"id\":\"19\"}" (cockpit.js, line 442)
</pre>
</details>

**Comment by hfoy** [comment]
Hi @martinpitt and @leomoty I tested some more and from my testing the following does not work:

- Safari on iOS 11.4.1, 12, 12.1 (16B5059d) all these versions throw similar errors which @leomoty posted above.
- Chrome (69.0.3497.105) on iOS 12 and 12.1 (I am unable to debug this one)

(Tested on iPad Mini 2 and iPhone 7 Plus)

However, both 172 and 178 works flawlessly when running macOS Mojave (10.14) with Safari 12.0 (14606.1.36.1.9).

**Comment by leomoty** [comment]
@martinpitt, any updates? I can help testing if needed.

**Comment by martinpitt** [comment]
Sorry, no, please don't expect any action from me here. I don't have any Apple hardware, and it's not clear at all what exactly happens/fails here.

**Comment by garrett** [comment]
I'd love for Cockpit to have proper iOS support, but can't help outside of WebKit fixes. (@larskarlitski and I both test Cockpit in WebKit periodically and make fixes when needed.)

I only have a MacBook Pro 5,3 from mid-2009 running OS X (macOS isn't available for it) and an iPad 1 (which is basically slightly more useful than a paperweight), so I can't really help out much.

FWIW: Every browser on iOS is WebKit. All non-Safari browsers are forced to use the same exact engine, including "Firefox". I'd suggest using the one with the best debugging tools, which is probably Safari.

**Comment by xkalibur** [comment]
I was able to make it work on iPad by setting AllowUnencrypted=true and using http. Presumably setting up a proper cert would work, too. I’m only using this over my home lan for now. Found a similar issue (regarding cockpit on iOS) via google circa 2016, that mentioned possible web socket issues with untrusted certs which led to this workaround.

**Comment by leomoty** [comment]
Since @xkalibur said that allowing unecrypted works, I am doing the opposite, I have a valid certificate for my cockpit instance. And I can confirm it works properly. Last time when I tried, I just used the raw ip (lazy).

**Comment by Bellusterra** [comment]
I was having the same issue with everything working fine over laptop/desktop but would get a white screen after logging in over mobile. I have a setup similar to this one:
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX

And found that changing the lines:
proxy_pass http://web socket; 
proxy_set_header Origin http://$host;
TO:
proxy_pass https://web socket; 
proxy_set_header Origin https://$host;

Fixed the issue on iOS.
Hope that helps someone.

**Comment by garrett** [comment]
So I got an iPhone 7 today for testing purposes and can reproduce this error.

I hooked it up to my very old MacBook Pro and managed to see the console log:

![Screenshot 2019-05-16 at 12 15 52](https://user-images.githubusercontent.com/10246/57846699-14aafb80-77d5-11e9-9d5e-74e00b94f6d8.png)

**Comment by garrett** [comment]
There's a possible fix mentioned at https://stackoverflow.com/a/39932753:

> I have this issue, too. Node https + express + socket.io, my web page is working fine on desktop safari, but not on mobile safari.
> 
> After stop grabbing and trying, I found the problem is "certificate chain". https://stackoverflow.com/a/20444809/6939828
>
> I'm using TWCA's ssl certification, after inject "ca: chain.cer" into options to https.createServer, same page same code just works on mobile safari. Hurray!

I don't know what it means though, as I don't have a clue about certificates or self-signed certs — aside from the fact that they exist and are needed for a secure connection. Perhaps @mvollmer, @martinpitt, @larskarlitski might know?

**Comment by leomoty** [comment]
Hey @garrett, I guess it is mostly a configuration issue. You can either issue a valid cert, like I did with Lets Encrypt. Or what @xkalibur did by allowing unencrypted connections. The latter is defined here:

https://cockpit-project.org/guide/149/cockpit.conf.5.html

> 

AllowUnencrypted | If true, cockpit will accept unencrypted HTTP connections. Otherwise, it             redirects all HTTP connections to HTTPS. Exceptions are connections from             localhost and for certain URLs (like /ping). Defaults to             false.
-- | --

**Comment by grregis** [comment]
I was having a similar issue.  I run docker on my server and my web server is run through a contatiner while I have cockpit on the main system.  I also am using LetsEncrypt for certificates as well.  

First, I transfered my LetsEncrypt cert to cockpit
`cat /etc/letsencrypt/live/cockpit.yoursite.com/fullchain.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert
cat /etc/letsencrypt/live/cockpit.yoursite.com/privkey.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert`

I also changed my /etc/cockpit/config.conf to the following
`cat /etc/letsencrypt/live/cockpit/fullchain.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert`

And here is my Apache conf
`<IfModule mod_ssl.c>
<VirtualHost *:443>
# The ServerName directive sets the request scheme, hostname and port that
# the server uses to identify itself. This is used when creating
# redirection URLs. In the context of virtual hosts, the ServerName
# specifies what hostname must appear in the request's Host: header to
# match this virtual host. For the default virtual host (this file) this
# value is not decisive as it is used as a last resort host regardless.
# However, you must set it for any further virtual host explicitly.
ServerAdmin admin@domain.com
ServerName cockpit.yoursite.com
ServerAlias www.cockpit.yoursite.com
DocumentRoot /var/www/html

# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the loglevel for particular
# modules, e.g.
#LogLevel info ssl:warn

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

ProxyPreserveHost On

# allow for upgrading to websockets
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://10.0.0.2:9090/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://10.0.0.2:9090/$1 [P,L]


# setup the proxy
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
ProxyPass / http://10.0.0.2:9090/
ProxyPassReverse / http://10.0.0.2:9090/
  
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"

SSLCertificateFile /etc/letsencrypt/live/cockpit.yoursite.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/cockpit.yoursite.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>`

Like I said, my webserver is on a docker container so the 10.0.0.2 is the local IP for server.  If you have both on the same machine you can probably substitute it for localhost.

**Comment by garrett** [comment]
We do have an error message with an installable certificate for Safari iOS now: https://github.com/cockpit-project/cockpit/pull/12493

However, you have to jump through hoops to "install" it into iOS. And then, at least for me on iOS 13 Beta 3, it doesn't work. :cry:

I don't know if there's much else we can do. I'll try again on iOS 13 beta 4. (Perhaps Apple might finally fix the issue for iOS someday? They fixed this same exact issue for macOS last year.)

**Comment by iandk** [comment]
Any news?

**Comment by garrett** [comment]
@iandk: Yep, [previous comment](https://github.com/cockpit-project/cockpit/issues/10146#issuecomment-533214828). However, while we got it working on the iOS simulator, I wasn't able to get this work-around working on iOS 13 on an actual iPhone.

This is a bug with Apple; we cannot fix this, only work around it.

The most proper solution is to use a valid certificate instead of attempting to use a self-signed one. Using a valid, non-self-signed certificate works without any workarounds.

Meanwhile, we now have a page that at least states the error and links to the certificate. (You have to have already accepted the certificate to see it. This is mainly for iOS, where websockets don't work on self-signed certs until installed into the system keystore manually.)

FWIW: I've tried again on iOS 13 release and it didn't work for me. The phone is now on iOS 13.1 and I'm about to update it to the 13.2 beta to see if they fixed it there finally. (I'm assuming no, as this issue has been on their end for several years now. At least they did finally fix it in macOS a year or so ago. However, macOS has the possibility of having browsers that aren't Safari. iPhones and iPads can only use one browser, Safari, so we're 100% at Apple's mercy here.)

**Comment by garrett** [comment]
FWIW, the problem has been around for at least a decade... https://bugs.webkit.org/show_bug.cgi?id=41419 (and this one is about minimally _logging_ that it doesn't work). This WebKit Bugzilla bug is a little more relevant: https://bugs.webkit.org/show_bug.cgi?id=145819

It has been fixed in all implementations of WebKit I've seen except for iOS / iPadOS. (That is, Apple finally fixed it in Safari macOS around a year ago and it has been fixed in open source WebKit browsers such as Epiphany as a result too.)

Meanwhile, I tested the certificate again in iOS 13.2 beta here and it still doesn't work. It's frustrating, and there's not much more we can do from our end. (Several of us on the team have spent many hours trying to get this to work.)

**Comment by mikey32230** [comment]
I've been trying to read through and follow this Issue thread. I see there are 2 workaround solutions:

- Allowing unencrypted connections via /etc/cockpit/config.conf as stated by @xkalibur
- Issue a valid cert (e.g. Lets Encrypt), place in /etc/cockpit/ws-certs.d/ @leomoty

1. I assume the cert still won't work for accessing via internal ip or internal hostname?

2. I'm failing to understand why this white screen issue is only really happening with cockpit, compared to other self-hosted web applications run over https without a valid cert? (e.g. shown the this connection is not private warning and continuing anyway.)

**Comment by martinpitt** [comment]
@mikey32230 : "Normal" https connections work with the certificate warning. The bug in Safari is that this "get me there anyway" override does not apply to websockets. So you can still see Cockpit's login page (which doesn't use websocket), but after login it fails because the cockpit protocol runs over websocket.

**Comment by leomoty** [comment]
@mikey32230 I do actually put my cockpit behind a reverse proxy (traefik), which is only available within the network.

To validate my claim to the domain I just use the DNS challenge method from Lets Encrypt (this is handled automatically by Traefik, just need configuration), so the application doesn't need external access.

I also set a DNS rule to say something like "cockpit.example.com" -> "internal ip".

**Comment by mikey32230** [comment]
@martinpitt Thanks for the simple explanation, that makes sense. I've now gone and googled a bit about websockets, never really understood that before. Nice to learn something new.

@leomoty Thank you for the further explanation. I have a similar setup to you with nginx as my reverse proxy server + letsencrypt in a docker container, although I don't have a need to reverse proxy cockpit.

If you request a valid cert I understand that accessing the site via domain name (e.g. https://cockpit.example.com) should work.
But that cert will still be invalid if you access the site directly at its internal ip (E.g. https://10.0.0.2:9090), right?

**Comment by leomoty** [comment]
@mikey32230 yeah, you'd need to place the cert in cockpit directly for that case.

**Comment by dld-r00f** [comment]
Nginx proxy with client certificate also does not work on iOS Safari. (server certificate from Lets Encrypt and client certificate with self signed CA installed on ios) The login page is fine, but WSS does not work at all.

**Comment by andrew-kennedy** [comment]
I'm also having issues with a self-signed client mTLS cert on iOS Safari. I cannot get cockpit to load with my reverse proxy forwarding to cockpit after accepting requests with mTLS. Login page works, WSS doesn't work. Have to disable the reverse proxy mTLS usage to make cockpit work on iOS. No issues with Chrome or Safari on desktop.

**Comment by garrett** [comment]
iOS Safari's websocket implementation doesn't work with self-signed certificates. macOS does. 

OS X WebKit has supported self-signed certificates with websocket for years now. Plus, on OS X / macOS, you can install other browsers, unlike on iOS. Unfortunately, there's only one browser available on iOS — Safari. (All other "browsers" are just custom shells around Safari WebKit.)

There's nothing at all we can do to fix iOS. We've tried everything, and so have other projects. It's 100% an Apple iOS issue (and has been since the iPhone has come out). We're all at the mercy of the Apple iOS WebKit developers here, as there's no choice on iOS.

I'm updating my test iPhone to iOS 14 beta, which has changed a lot of WebKit specifically. Hopefully they've finally fixed this bug. I'll report back if they have or have not.

Meanwhile, if you want iOS support with Cockpit (or anything else that requires websocket support), you have four options:
1. Run over HTTP. (Not ideal whatsoever, and we do not suggest doing this, for obvious reasons.)
2. Use a proper certificate from a CA. (Not always possible.)
3. Use Android or a desktop OS, where it works. (Not always possible.)
4. Wait and hope for Apple to finally fix their longstanding bug.

**Comment by garrett** [comment]
That all said, you shouldn't be getting a black screen on any browser. We changed Cockpit a while back to show an error message.

What version of Cockpit are you using?

**Comment by garrett** [comment]
Update: iOS14 WebKit's websocket _still_ does not work with self-signed certificates. :cry:

**Comment by garrett** [comment]
@andrew-kennedy FWIW: macOS Safari _should_ still work with self-signed certs, unless Apple had a regression in the latest version of macOS. (I've tested the previous version on my old MacBook and it worked fine. It also worked fine in the latest few versions OS X.)

**Comment by garrett** [comment]
Note:

> 2. Use a proper certificate from a CA. (Not always possible.)

You can use a letsencrypt cert if your host is Internet-facing. Otherwise, you _should_ also be able to use a companywide cert, if it is a legitimate certificate (and not a self-signed one).

This is really the only proper solution I'm aware of, aside from Apple fixing their issues.

**Comment by leomoty** [comment]
@garrett I've used letsencrypt on my local network with success, you just need to use DNS challenge instead of HTTP one to reverify the certificate. Keep in mind, I am using a load balancer (Traefik) that autorenews it.

**Comment by andrew-kennedy** [comment]
> That all said, you shouldn't be getting a black screen on any browser. We changed Cockpit a while back to show an error message.
> 
> 
> 
> What version of Cockpit are you using?

I do indeed get an error message, and I'm using cockpit version 223 on fedora 32. Strangely though you claim macOS Safari does not have the websocket bug, I do get the same error screen as iOS.

**Comment by andrew-kennedy** [comment]
Just opened the javascript console on macOS safari, and I get `WebSocket network error: The operation couldn’t be completed. (OSStatus error -9825.)`, which according to OSStatus.com translates to `errSSLPeerBadCert`. I'm guessing it's a regression in desktop Safari.

**Comment by garrett** [comment]
Apple fixed it in Mac OS X years ago (before the rename to macOS). 

I just confirmed that Cockpit works with a self-signed certificate on macOS Safari 10.15.3 (I need to update this test box). So, if it is a regression, then it would be either in .4 or .5. Otherwise, it might not like your certificate for other reasons. I don't have a proxy in the middle, for example. This is simply Cockpit and its own autogenerated self-signed certificate.

Safari on macOS is definitely pickier than other browsers when it comes to certificates, but it's not nearly as picky as iOS.

**Comment by martinpitt** [comment]
This bug is rather stale, and the last comment validated that it works with current MacOS.

**Comment by garrett** [comment]
> This bug is rather stale, and the last comment validated that it works with current MacOS.

The problem isn't with _macOS_, the desktop OS, (which was fixed years ago at this point), but with _iOS_, which is used on iPhones and iPads (as stated in the title of the issue). And on iOS it's still a problem. 

They both use Safari WebKit, but it's a different version of WebKit on each, with (obviously) a different certificate store.

**Comment by garrett** [comment]
There's yet a new version of iOS coming soon (4.5) and I'll test it yet again. Hoping that Apple fixed it, but not optimistic about it. But who knows?

**Comment by Nochalek** [comment]
Is this Bug still really a thing for THAT LONG?

**Comment by garrett** [comment]
@Nochalek: Yes, it is. We're still waiting on Apple to fix it. It's 100% on their end. It's depressing.

There's nothing we can do (and we've tried all sorts of things, spending hours trying to figure out some kind of workaround).

I've tested it every single iOS release, except the brand new one that came out in the past week. I'm planning on checking again soon.

**Comment by garrett** [comment]
Note: It's not just Cockpit that's broken on iOS. It's every single website and web app that uses wss (secure websockets) with a self-signed or custom certificate. Cockpit is just one of many web apps that's affected. (There are tons of threads out there for other products, but nobody has a solution.)

I'd recommend using a different browser on iOS meanwhile, except there's only Safari. Every other "browser" on iOS is still just Safari's own WebKit but with a few different widgets around it. (That goes for "Firefox", "Chrome", "Brave", etc. On iOS, they're all just Safari at their core.) Meaning: There's not even a workaround, due to Apple's limiting of browser engines to their own.

**Comment by garrett** [comment]
OK, I booted up my test iPhone and it still has the same bug. It's still not fixed. Sorry. There's really nothing else we can do.

(We have made it so there's an explanation page and not a blank one since this bug has been open, but that's the extent of what we're able to do. But it's not useful, as the certificate, even when manually imported, is still not respected by Safari on iOS. Still. Even as of today.)
 
This is the result of what happens when a tech company has a 100% proprietary stack and gatekeeps their silo to not allow any competitors to port their software over. :cry:

**Comment by Nochalek** [comment]
@garrett There is no way to workaroud it, what about working it around with some kind of Jailbreak cydia tweak?
I suppose there is no other option.

**Comment by garrett** [comment]
@Nochalek: Asking our users to break the security of their phones is not really an option. 

Yes, in most cases, it's fine and safe enough to jailbreak, but they can also add bad stuff to their phone too. And it requires not just risk, but technical know how and willingness to do so. Additionally, if a user of ours is using Cockpit for their workplace, they are probably not even allowed to do so. 

They really need to know what they're doing when jailbreaking. (It can compromise security and be tricky to do so.) It's just like for those who use third party ROMs on Android, which, thankfully isn't necessary on Android to run 3rd party browsers.

---

The _real_ alternative option is to use a legit certificate from LetsEncrypt or any other CA that is recognized by the iPhone. (That's either tricky or impossible for some machines behind a firewall though.)

That is, until Apple finally fixes their bug and/or allows 3rd party browser engines on their iOS/iPadOS platform.

**Comment by garrett** [comment]
Note: I tested this with iOS 14.5 and I see there's a beta for 14.6. (I've been testing with every beta and release in the hopes that this is finally fixed.) I'll upgrade to the 14.6 beta. Who knows? Maybe they'll fix it someday.

(This was previously a problem on OS X too, and they fixed it, even before "OS X" became "macOS"... yes, that long ago. However, iOS Safari is different from macOS Safari, and they use different certificate storage and apparently secure websockets (wss) is still implemented differently.)

**Comment by jonaharagon** [comment]
Are you sure this is not an issue on current versions of macOS either? I am running into this bug on an M1 MacBook Air running macOS 11.4 Beta (20F5046g), Safari 14.1.1.

**Comment by Nochalek** [comment]
> Are you sure this is not an issue on current versions of macOS either? I am running into this bug on an M1 MacBook Air running macOS 11.4 Beta (20F5046g), Safari 14.1.1.

I can confirm that it works for me on an Intel MacBook Air. I have No idea about M1 tho

**Comment by FLIPNEUS** [comment]
What solved a lot of issues for me was enabling the Experimental NSURLSession WebSocket setting on both iOS and macOS. This setting became available in iOS14 and macOS Big Sur. I don’t even need a valid certificate with this setting turned on.

![3B75C22A-0D3A-4198-B0DB-5F1A1C8188BF](https://user-images.githubusercontent.com/7464548/118215623-1db81d00-b42f-11eb-8ee3-cdcd2b011291.jpeg)

**Comment by nlights** [comment]
> What solved a lot of issues for me was enabling the Experimental NSURLSession WebSocket setting on both iOS and macOS.

Thank you very much – works for me now, too!

**Comment by garrett** [comment]
@FLIPNEUS: Oh, this is great! Thanks for the tip. I'll check it out next week here as well. Glad to see it's working for you and @nlights. If it works for me as well, I think we should have a note about it on the website and documentation.

Hopefully Cockpit is already good enough on iPhones. I've been testing WebKit and mobile sizes independently, so it should be _theoretically_ fine. But with this workaround, I'll be able to test it properly on an iPhone too (and hopefully come up with fixes and optimizations quickly if anything is broken).

**Comment by garrett** [comment]
Wow! This works here too! Thank you so much, @FLIPNEUS!

OK, I'll have to document this and get it on the website. I have noticed a few small glitches, but everything (that I've tested so far) seems to work quite well! :tada:

@jonaharagon: Can you check to see if you have the "NSURLSession WebSocket" option under experimental / advanced on macOS too, and if that helps? (Thanks in advance!)

**Comment by jonaharagon** [comment]
Nice, that totally works on my MacBook Air as well. I tested this on my work iMac (Intel) as well, and I agree with everyone else that changing this setting is not necessary on an Intel Mac (FWIW, the setting _exists_ but on Intel it works disabled, for whatever reason). 

I have an M1 MacBook Pro as well that I just wiped, so it should be back to defaults. I'll try this later on that machine to confirm my MacBook Air isn't just weird (since nobody else here has an M1 Mac?) and report back.

Here's some screenshots for your PR too, since the menu is disabled by default on macOS:

Safari Preferences > Advanced > Show Develop menu in menu bar

<img width="904" alt="2021-05-18 at 12 45 16@2x" src="https://user-images.githubusercontent.com/3637842/118699224-e783f000-b7d6-11eb-9bb0-86a1033c301e.png">

![2021-05-18 at 12 50 25@2x](https://user-images.githubusercontent.com/3637842/118700023-cc65b000-b7d7-11eb-8ca7-3ed36ccc0fcd.png)

**Comment by garrett** [comment]
> I have an M1 MacBook Pro as well that I just wiped, so it should be back to defaults. I'll try this later on that machine to confirm my MacBook Air isn't just weird (since nobody else here has an M1 Mac?) and report back.

@jonaharagon: Cool! Thanks! Are you happy with us including these screenshots on the website under the MIT license?

**Comment by garrett** [comment]
I have a pending PR that adds a page for iOS/iPadOS @ https://github.com/cockpit-project/cockpit-project.github.io/issues/410

If anyone's eager to see it in action, I set up a preview @ https://garrett.github.io/cockpit-project.github.io/running/safari.html. We'll probably merge it in at some time today.

**Comment by martinpitt** [comment]
Our [Install](https://cockpit-project.org/running.html) web page now leads to https://cockpit-project.org/running/safari.html which describes how to set up Safari to work with cockpit. This is about everything that we can do about this, I'm afraid.
