### ISSUE TITLE
Lots of "refused to apply inline style" warnings

### ISSUE THREAD

**Issue by paulhargreaves** [cockpit-project/cockpit#14123]
Cockpit version: 219
OS: Arch
Page: All after logging in.

Lots of security console errors + 404 errors are being logged by the browser.
E.g. 

`DevTools failed to load SourceMap: Could not load content for http://10.6.6.31:9090/cockpit/$57435d99001f58147ebf05c646510d8ca834b17de455fec3631dd259032910f5/base1/jquery.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

`index.js:15 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' http://10.6.6.31:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

etc.

No extensions are active (other than google docs, the default).

Steps to reproduce

1. Log in.
2. (Chrome) Right click->Inspect.
3. View console messages.

**Comment by martinpitt** [comment]
Right, this is a known issue that we inherit from PatternFly: https://github.com/patternfly/patternfly-react/issues/2919 . This was fixed recently, and once that makes it into a release that should be gone.

**Comment by LivArt01** [comment]
I also have this issue - 229-1~bpo10+1 on Raspbian.

**Comment by KKoukiou** [comment]
I this this is not happening any more? @marusak @martinpitt did you notice any warning about inline styling lately?

**Comment by martinpitt** [comment]
I still see this with 237 right after login:

    Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 index.js:25:35361

**Comment by LivArt01** [comment]
For me it's still happening: 
![Error image](https://i.postimg.cc/gk9MCrH6/Sni-mek-obrazovky-2021-02-13-v-7-23-11.png)
Version 237.

**Comment by thkruz** [comment]
Fresh install of version 254 and I am getting this too...
![cockpit-error](https://user-images.githubusercontent.com/23319161/136666528-fd0b6e53-033d-432d-a455-d8be897806f8.png)

**Comment by KKoukiou** [comment]
Not present with 282.
