### ISSUE TITLE
The filesystem has no permanent mount point.

### ISSUE THREAD

**Issue by dvardy** [cockpit-project/cockpit#14260]
Cockpit version: 211.3
OS: CentOS Linux release 8.2.2004 (Core)
Page: Storage > Drives

Under the Storage > Disk > Contents page, it is saying that there is no permanent mount point and will not be mounted at next boot. Reboots have been performed and the disks will mount.

I suspect this might be due to the mounts being handled by systemd rather than stored in fstab. All mounts handled by fstab are not showing a warning and all mounts handled by systemd are.

![image](https://user-images.githubusercontent.com/64214484/85306560-92483d00-b4a6-11ea-8f66-da2f99981de8.png)

**Comment by mvollmer** [comment]
> I suspect this might be due to the mounts being handled by systemd rather than stored in fstab. All mounts handled by fstab are not showing a warning and all mounts handled by systemd are.

Yes, this is exactly the reason. We should fix that... in Cockpit or in UDisks2.

**Comment by Zylatis** [comment]
I think i actually have the inverse problem. I have mounted an external drive in fstab using the UUID from lsblk (if i put the PARTUUID in fstab then i don't see the drive in df for some reason)

Anyway, even though it's in fstab i still get that warning.

**Comment by koenemans** [comment]
Bumping the issue. Still persistent on Rocky Linux 10:
```
cockpit 344
cockpit-bridge 344
cockpit-machines 337
cockpit-podman 111
cockpit-storaged 344
cockpit-system 344
cockpit-ws 344
cockpit-ws-selinux 344
```

**Comment by jelly** [comment]
This is a duplicate of https://github.com/cockpit-project/cockpit/issues/18654
