### ISSUE TITLE
Error "Not Found" after login on Cockpit after change the user shell (from /bin/bash to /bin/fish)

### ISSUE THREAD

**Issue by eduardonunesp** [cockpit-project/cockpit#14897]
Cockpit version: cockpit x86_64 211.3-1.el8
OS: CentOS Linux release 8.2.2004 (Core)
Page: After login 

After changing the default shell from my user running the command  `chsh` the login on cockpit started failed with "Not found"

<img width="389" alt="image" src="https://user-images.githubusercontent.com/582516/98960633-6c6a1600-24e3-11eb-89f1-045f55a1e494.png">

Steps to reproduce

1. Install `fish shell` from `EPEL repo`
2. From your user run `chsh` from `/bin/bash` to `/bin/fish`
3. Restart cockpit `systemctl restart cockpit` 
4. Try to login again, after successful login the error will happen

**Comment by garrett** [comment]
I've been using fish here for some time now (since fish 3.0.x, around December 2018) on Fedora. I have my shell set to /bin/fish (although `which fish` shows `/usr/bin/fish`) and haven't any issue. But I have Cockpit built from sources here for development. And I also have both Cockpit and fish on my home ARM server running Ubuntu 20.04.

I wonder if this is CentOS / EPEL specific? And, in that case, it probably hits RHEL + EPEL too. And I'd bet it might affect zsh users as well (although that's POSIX enough that it might night).

Does changing your shell back to `/bin/bash` make Cockpit work again for you?

**Comment by eduardonunesp** [comment]
yep changing the shell back to `bash` makes Cockpit works as expected, well this is not a bummer, actually, my intent is just let this experience documented here to help any other user that stuck on that "issue"

**Comment by garrett** [comment]
Does anything look fishy in your logs? (Pardon the pun.)

Can you check `journalctl -xe` when this happens?

Meanwhile, I've made a fresh installation of CentOS 8 in GNOME Boxes and will install Cockpit and switch shells to see what happens here.

**Comment by garrett** [comment]
@eduardonunesp: What page are you viewing in your browser? Is it the overview one? It would look something like this:
`https://YOUR_HOSTNAME_OR_IP_ADDRESS_HERE:9090/system`

I've:
1. installed CentOS 8
2. enabled EPEL and PowerTools as described here: https://fedoraproject.org/wiki/EPEL
3. installed fish
4. chsh to /bin/fish (after letting yum install util-linux-user to provide chsh)
5. rebooted

And Cockpit still works.

I've only changed my own shell, not root's. Have you changed root too? Or just your own?

Note: I _did_ make the mistake of running the RHEL 8 commands on the EPEL page too, with the subcription manager, and it did make the software page think my CentOS system needed to be registered for updates. And I did click on the button to see what happened, as it's not actually a RHEL system. But once I removed `subscription-manager` with yum, even the updates page worked as expected. Well, I did get a "not found" error page after signing out and back in on the same registration page, but all the other pages worked, including the overview at `/system` (default page).

What cockpit-* packages do you have installed? Did you just install the standard `cockpit` one (and its dependencies), or do you have any additional ones installed too?

**Comment by eduardonunesp** [comment]
I installed the cockpit from the latest `CentOS 8`, then later added the `EPEL` and installed `fish`. I was changed the shell from my non-root user and tried to log with that user on `cockpit`. I had installed all available on the default repo.

**Comment by eduardonunesp** [comment]
The issue happened right after a success login with my non-root user

**Comment by garrett** [comment]
This is really odd. I cannot reproduce it.

Have you tried running `yum upgrade` to make sure everything is at the latest version?

**Comment by garrett** [comment]
Do you have a customized fish set up? Perhaps there's something in your config that might be messing up Cockpit.

I've only tested with fish's defaults in CentOS 8. (Although my own workstation has a lot of configuration, including omf and a bunch of custom commands and such, and it still works here.)

Are you able to create a temporary custom user and test things there?

**Comment by eduardonunesp** [comment]
Hhummmm maybe my config file `~/home/myuser/.config/fish/config.fish`, with the some config like
```bash
# Some paths
set -x GOPATH $HOME/.go
set -x CARGOPATH $HOME/.cargo

# Put all together
set -x PATH $PATH $CARGOPATH/bin $GOPATH/bin
```

**Comment by eduardonunesp** [comment]
If you can't reproduce let's close this issue, and hope (or not) that someone stumble on this issue in the future

**Comment by garrett** [comment]
On the other hand: If you're able to figure out why it's different on your system versus mine, then we can address the issue.

Someone else who may hit this with fish (or zsh or some other shell) might not report it; it'd be great to fix the bug before they'd see it.

**Comment by mvollmer** [comment]
FWIW, I can't reproduce this either.  Can you show the Browser logs to see which URLs it is loading exactly?

**Comment by mvollmer** [comment]
Also, looking at the diff between the output of `env` might give some ideas.  This is, run `env` once with bash when Cockpit works, and then again with fish when Cockpit fails. Try making them more similar, especially $PATH and any $XDG_foo variables.

**Comment by martinpitt** [comment]
This was fixed in commit 2044cde5889641e363dc924a91bc19d3ffb979c3 in version 226.

**Comment by NeV3rKilL** [comment]
I'd like this to be reoponed. Happened again. I had to change from Fish to Bash in order to have cockpit working. 

Ubuntu-server version:
$ dpkg -l | grep cockpi
ii  cockpit                                215-1                                                       all          Web Console for Linux servers
ii  cockpit-bridge                         215-1                                                       amd64        Cockpit bridge server-side component
ii  cockpit-dashboard                      215-1                                                       all          Cockpit remote servers and dashboard
ii  cockpit-doc                            215-1                                                       all          Cockpit deployment and developer guide
ii  cockpit-networkmanager                 215-1                                                       all          Cockpit user interface for networking
ii  cockpit-packagekit                     215-1                                                       all          Cockpit user interface for packages
ii  cockpit-pcp                            215-1                                                       amd64        Cockpit PCP integration
ii  cockpit-storaged                       215-1                                                       all          Cockpit user interface for storage
ii  cockpit-system                         215-1                                                       all          Cockpit admin interface for a system
ii  cockpit-ws                             215-1                                                       amd64        Cockpit Web Service

**Comment by marusak** [comment]
> This was fixed in commit https://github.com/cockpit-project/cockpit/commit/2044cde5889641e363dc924a91bc19d3ffb979c3 in version 226.

> I'd like this to be reoponed. Happened again.
...
>  cockpit 215-1 

215 < 226

Please update your system. Since you are on ubuntu, please use backports. https://cockpit-project.org/running.html#ubuntu

**Comment by NeV3rKilL** [comment]
That did not work. It updated to backports, but then i had:

"Unit cockpit-wsinstance-http-redirect.socket not found"

I'm just creating another user with bash shell and using it in cockpit.

**Comment by LunarN0v4** [comment]
Still happening, this time on Debian 12 with backports installed.
System is up to date as well.
root@vps:~# dpkg -l | grep cockpi
ii  cockpit                                       287-1                              all          Web Console for Linux servers
ii  cockpit-bridge                                287-1                              amd64        Cockpit bridge server-side component
ii  cockpit-doc                                   287-1                              all          Cockpit deployment and developer guide
ii  cockpit-networkmanager                        287-1                              all          Cockpit user interface for networking
ii  cockpit-packagekit                            287-1                              all          Cockpit user interface for packages
ii  cockpit-pcp                                   287-1                              amd64        Cockpit PCP integration
ii  cockpit-sosreport                             287-1                              all          Cockpit user interface for diagnostic reports
ii  cockpit-storaged                              287-1                              all          Cockpit user interface for storage
ii  cockpit-system                                287-1                              all          Cockpit admin interface for a system
ii  cockpit-ws                                    287-1                              amd64        Cockpit Web Service

**Comment by martinpitt** [comment]
@LunarN0v4 I suppose that was your issue #19165 ?

**Comment by LunarN0v4** [comment]
> @LunarN0v4 I suppose that was your issue #19165 ?

yes, turns out, config was effed

**Comment by NickJi2019** [comment]
try to delete /etc/cockpit/cockpit.conf, then restart the service.
for newly installed cockpit on CentOS that file should't exist
