### ISSUE TITLE
Filesystem, used and total size based on different units

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#1562]
![screen shot 2014-12-05 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/10091077/5321843/82626af4-7c7c-11e4-92a1-f18472403790.png)

See the first line for mount point /boot. The first value is for used, and is based on binary prefix (the number is in mebibytes); the second value is for total, and is based in SI prefix (the number is in megabytes).

Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda2         487652  188894    269062  42% /boot
/dev/sda2       477M  185M  263M  42% /boot                     ## -h

I don't care whether cockpit uses binary or SI prefix, but it should pick one, and show the correct unit. The easiest fix right now is for the first (used) size value to be based on SI units, and then the MB and GB don't need to be changed to MiB and GiB, etc.

**Comment by dperpeet** [comment]
There are two issues here to make this truly consistent:

1. The formatting function in [cockpit.js](https://github.com/cockpit-project/cockpit/blob/e5c25b4bba4504c3bde10b64784a2bfffbccec74/pkg/base/cockpit.js#L2227). It defaults to binary units (1024), but the [suffixes](https://github.com/cockpit-project/cockpit/blob/e5c25b4bba4504c3bde10b64784a2bfffbccec74/pkg/base/cockpit.js#L2221) are identical, the binary ones are commented out. Is there a reason for this? It would make inconsistencies more readily apparent.
2. A quick grep shows that in the packages, shell among them, format_bytes is called with different units (1000, 1024). We should pick one!

Is there a reason for most packages to have hardcoded units? (SI vs binary) If they used the default, this could conceivably be converted to a user setting without changing the individual packages.

**Comment by stefwalter** [comment]
Lets fix this to be consistent first, and file other bugs for issues you find.

 * The design guys said we shouldn't be using textual binary suffixes (MiB, GiB, etc...)
 * Some things (like network speed) are always measured in SI units (never binary), it will always be necessary to call these with the `1000` units.

**Comment by stefwalter** [comment]
format_bytes() documentation here: http://files.cockpit-project.org/guide/latest/api-cockpit.html#latest-format-bytes

**Comment by dperpeet** [comment]
If we use SI suffixes, then I believe we should switch to base 10 with the numbers, as well. I will change the code accordingly (without changing the default in [format_bytes()](http://files.cockpit-project.org/guide/latest/api-cockpit.html#latest-format-bytes)

**Comment by mvollmer** [comment]
Note that @cmurf said that in "184.5 / 499.5 MB" the "184.5" is in MiB, and the "499.5" is in MB.  That would be a bug in our formatting routines, regardless of what units different parts of the code choose.

**Comment by dperpeet** [comment]
I believe I fixed this when I changed all calculations to binary representation. Did I miss anything? The lowlevel formatting routines seem fine.

**Comment by cmurf** [comment]
Login > host.localdomain > Storage > under Filesystems is an ext4 volume is reported as 238.0 / 499.4 MB

The first value is almost certainly MiB(IEC), the second value is almost certainly MB(SI). [1]

Next, if I click anywhere on this line, I'm taken to a page about this particular (physical) drive, under Content it lists the four partitions, the partition for the example volume is described as a 500.0 MB Partition. This must be MiB(IEC) units since parted reports the partition size as 1024000s, which 1024000 * 512 / 1024 / 1024 = 500.0 MiB(IEC).

[1] Showing my work to determine this

# stat -f /mnt
  File: "/mnt"
    ID: 78015679fd5829b Namelen: 255     Type: ext2/ext3
Block size: 1024       Fundamental block size: 1024
Blocks: Total: 487652     Free: 243895     Available: 214199
Inodes: Total: 128016     Free: 127657

# df /mnt
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/sda2         487652 243757    214199  54% /mnt

stat Blocks Total 487652 minus Blocks Free 243895=243757 (consistent with df, contrast to stat Blocks Available 214199); 243757 / 1024 = 238.0439 MiB(IEC).

stat Blocks Total 487652 * 1024 / 1000 / 1000 = 499.355648 MB(SI).
------
It's really easy to get this confused because the underlying commands all do this differently. It caused a lot of frustration for python-blivet devs when reworking it for anaconda 21, and I'm pretty sure what they've done is normalize to bytes to do addition/subtraction and then convert to desired units. Python-blivet might be overkill for cockpit as a storage backend now, but I see things like formatting, creating volume groups, RAID, and python-blivet already knows how to do all this stuff including a lot of Btrfs support. 

Default install of Fedora 21 Server appears to already have python-blivet installed.
# rpm -q python-blivet
python-blivet-0.61.13-1.fc21.noarch

**Comment by dperpeet** [comment]
Did you use the current build?
When I create a 1MiB image, I get the following:
![image](https://cloud.githubusercontent.com/assets/8711649/5642733/faeb3abe-964e-11e4-9775-76a99e03c880.png)

The figures are calculated from bytes via division. Please note loop2 - if either used or total capacity were in SI, the display would switch to MB instead of KB.

Also note the details:
![image](https://cloud.githubusercontent.com/assets/8711649/5642753/482d6ad6-964f-11e4-8034-1163d5951555.png)

vs.
![image](https://cloud.githubusercontent.com/assets/8711649/5642755/560b8de0-964f-11e4-954d-25841855b390.png)

Both use binary units as expected.

The filesystem capacity is lower than the device capacity - but that is expected due to filesystem overhead. How much depends on the filesystem and its parameters for the specific device/image.

**Comment by cmurf** [comment]
I haven't tested from master yet. I'll report back if I still see bugs. Two points though:

1. If the unit label will be KB, MB, TB, then the unit values need to be SI based. In your example, the values are IEC units, therefore the labels should be KiB, MiB, TiB. It's no long a quaint difference in convention, it's a NIST requirement, as well as IEC and BIPM saying that the SI labels (KB,MB,TB etc) cannot be used to for 1024 (binary) units.

2. For me personally, it's a coin toss whether storage units are IEC or SI based. There's a slight advantage using SI for the whole device since that's the value found on the drive and the box it comes in. So it could be advantageous wherever the drive appears along with its make/model info that the size value is based on SI units.

**Comment by cmurf** [comment]
cockpit-0.41-1.fc22.i686

This is still a bug. The UI uses the letters "GB" but the numeric values are in GiB. See screenshot.
![screen shot 2015-03-04 at 7 24 32 pm](https://cloud.githubusercontent.com/assets/10091077/6498038/4ffff4a0-c2a4-11e4-85c9-da98ad5161eb.png)
UI shows /dev/sda2 5.9GB, however 'parted <dev> u s p' shows
Number  Start      End         Size        File system  Name  Flags
 2      4096s      12351487s   12347392s   xfs
12347392x*512bytes=6321864704bytes=5.887GiB or 6.321GB

Ergo, the UI is using GiB for numeric values but is wrongly labeling them "GB".

**Comment by stefwalter** [comment]
> Ergo, the UI is using GiB for numeric values but is wrongly labeling them "GB".

Yes, this was the decision made here #704 and implemented here #869

It's one of those situations where it's impossible to please everyone :S

**Comment by cmurf** [comment]
It's not about pleasing people, especially not me. It's about standards. The current behavior is contrary to SI, IEC and NIST. It's contrary to the work being done to fix this confusion by various projects.

julienlim gave you bad advice. 

Some projects made their choice before there was a big push to unwind this confusion. Some projects don't have many developers either, to do this sort of work.

Instead of julienlim et al convincing you to do the wrong thing, they should go put in some effort to encourage, or work on, migrating old tools that do things wrong so they can do them correctly.

4+4 is 8, it is not 7.8125. OK I'll get off the soapbox and give some examples:


The Btrfs folks offer both, -h is binary, -H is metric, and binary is the default e.g:
$ btrfs fi df -h /
Data, single: total=6.01GiB, used=4.25GiB
System, DUP: total=8.00MiB, used=16.00KiB
System, single: total=4.00MiB, used=0.00B
Metadata, DUP: total=1.00GiB, used=239.97MiB
Metadata, single: total=8.00MiB, used=0.00B
GlobalReserve, single: total=80.00MiB, used=0.00B
$ btrfs fi df -H /
Data, single: total=6.45GB, used=4.56GB
System, DUP: total=8.39MB, used=16.38kB
System, single: total=4.19MB, used=0.00B
Metadata, DUP: total=1.07GB, used=251.62MB
Metadata, single: total=8.39MB, used=0.00B
GlobalReserve, single: total=83.89MB, used=0.00B

So without -h I get the same results as -h.

Julienlim points to anaconda. Well, he's right in CentOS 7 but that predates recent work in Fedora 21 to fix the units problem. They now use KiB, MiB, GiB. The user, however, can input anything: 10B, 10KB, 10KiB are three different things and the code does the conversion (bytes on the backend, and binary units in the UI; so user can input metric if they want to but this gets correctly converted to binary units).

Very cool: The Anaconda team just split out this work from python-blivet into its own package, python-bytesize. So that might be useful when you get around to re-fixing this. I still think python-blivet is useful for Cockpit down the road because it does all the RAID, LVM, Btrfs stuff that udisks doesn't support. Less work reinventing that wheel.

Next julienlim says LVM. Except... Fedora 21 VM, the lvs and lvdisplay commands are all using binary units and showing this with MiB, GiB etc.

  --- Logical volume ---
  LV Path                /dev/VG/home
  LV Name                home
[..snip..]
  LV Size                50.00 GiB
  Current LE             12800
[...snip...]

lvs reports this as "50.00g" under LSize volume, so that's ambiguous because g is not a unit. It should be GiB of course, they probably do g to same space with their column output format. 

But I see no use of KB, GB, MB. And by the way, another bone to pick, KB is always wrong. The K means Kelvin, whereas k means kilo. So no matter what, KB is completely utterly wrong, there is no defending that. Tell these julienlims if they don't like it, they can go argue with the standards bodies


OK what about parted? parted gets it right too, but they use metric
$ parted /dev/sdd u s p
Model: ATA VBOX HARDDISK (scsi)
Disk /dev/sdd: 512000000s
$ parted -l /dev/sdd
Model: ATA VBOX HARDDISK (scsi)
Disk /dev/sdd: 262GB

In fact 512000000s is 262144000000 bytes and hence 262GB is correct.


Aha the fdisk folks are in some amount of hot water:
$ fdisk -l /dev/sdd
Disk /dev/sdd: 244.1 GiB, 262144000000 bytes, 512000000 sectors
[...snip..[
Device       Start       End   Sectors   Size Type
/dev/sdd1     2048      4095      2048     1M BIOS boot
/dev/sdd2     4096   1028095   1024000   500M Linux RAID
/dev/sdd3  1028096 511999966 510971871 243.7G Linux LVM

OK so they do the Disk value correctly, 244.1 GiB is correct. But then they drop the ball and use M and G for units, similar to LVM folks using m and g. Those aren't byte units at all, they're just letters and hence mean nothing.

Anyway, you were given royally bad advice. Stick to the standards bodies and then you can tell people to go complain to the authorities rather than asking you to do weird non-standard things like this.

**Comment by cmurf** [comment]
And as for i18n, I would eat a billy goat if the ICU were to contradict either the IEC, NIST, or re-define SI units. So near as I can tell, this is not an i18n issue at all.

**Comment by stefwalter** [comment]
Pleas comment on the actual bug #704, and CC the participants there if you want to restart that discussion.
