### ISSUE TITLE
Networking tab doesn't show any network speeds anymore

### ISSUE THREAD

**Issue by chokonmainatsu** [cockpit-project/cockpit#19627]
### Explain what happens

1. Open browser Inspect tool/console
2. Open Networking tab
3. Speed graph shows 0 Kbps
4. Notice some errors in the console

The network speed were always shown up until a few weeks ago, I didn't really change anything major. The only things I'm regularly doing are updates.

There are also a few Network related errors in the browser console, not sure if they are relevant.

Just let me know if I can provide any further information.

![image](https://github.com/cockpit-project/cockpit/assets/68794729/d03a0c5f-a8e8-47d2-9857-a1c79f0677bf)

![image](https://github.com/cockpit-project/cockpit/assets/68794729/03dd3478-f32b-4b93-b7c6-6a5f406782ae)

Here in the Overview tab, the transfer speed is visible, not exactly accurate but good enough
![image](https://github.com/cockpit-project/cockpit/assets/68794729/6f1fa08b-0bd5-4480-948f-8892e0822751)

### Version of Cockpit

303-1~bpo22.04.1

### Where is the problem in Cockpit?

Networking

### Server operating system

Ubuntu

### Server operating system version

Ubuntu Server 22.04

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Interesting, I can reproduce this issue. These metrics come from the Python bridge to which we recently switched but it seems either our automated or manual testing didn't notice this issue.

**Comment by jelly** [comment]
Debugging locally shows that we do get metric changes when I enable `cockpit.debugging = 'channel'`. So this seems to have to do with the JavaScript code.

**Comment by jelly** [comment]
Interesting, a test VM works. But my laptop connected to WiFi does not, interestingly also has bridges configured.

VM has:
```
cockpit-ws-305.dev0+gf482c1c87-1.fc39.x86_64
cockpit-305.dev0+gf482c1c87-1.fc39.x86_64
```

Laptop has `main`.

**Comment by purpleboar** [comment]
I have only recently installed cockpit on an Ubuntu server but had not had any network or storage graphs. I installed diagnostic reports (cockpit-sosreport) and created the report. One the report had run I now had both graphs displaying correctly, with historic data going back to when cockpit was installed on the server.

**Comment by chokonmainatsu** [comment]
I've just tried the same, installing cockpit-sosreport and then running it.

This didn't have effect on the graphs on my machine.

**Comment by champtar** [comment]
Also happening on Alma 9.3 / cockpit-300.3-1.el9_3.x86_64

**Comment by vizaie** [comment]
Similar issue on arch
Cockpit version - 308-1

Network speed is not working for wireless Interface but ethernet Interface is working. Interestingly after connecting ethernet and removing it wireless interface speed started working. 

![Screenshot_20240116_101016](https://github.com/cockpit-project/cockpit/assets/58224705/c91d06df-d196-42ac-8d02-4450adeb6fc7)
![Screenshot_20240116_101311](https://github.com/cockpit-project/cockpit/assets/58224705/94862602-1caf-4d97-8911-d65964ac35af)



Is it because I installed the  below packages ?
cockpit-storaged cockpit-packagekit cockpit-podman cockpit-machines cockpit-pcp

**Comment by vizaie** [comment]
After removing cockpit-pcp, it stopped working
![Screenshot_20240116_103330](https://github.com/cockpit-project/cockpit/assets/58224705/d1bddf20-dfab-4fb9-bb27-ac8f551d76ee)

After reinstalling it, it started working. I guess you need cockpit-pcp, I didn't install it because it was in Optional deps.

**Comment by jciesla** [comment]
Same issue for me too. I don't have PCP installed because I'm on an embedded system, so I'm currently stuck to the cockpit 300.x version.

**Comment by RealYukiSan** [comment]
I have confirmed, installing `cockpit-pcp` package solve the graph issue on the chart (I didn't install `cockpit-sosreport`).

thanks @vizaie!

**Comment by november781** [comment]
on Fedora, installing cockpit-pcp downgrades cockpit-bridge. After installing cockpit-pcp networking activity works properly.

However, dnf immediately wants to replace cockpit-pcp with the updated cockpit-bridge. If this update is performed, the graphs stop working

**Comment by jelly** [comment]
These days you want to install python3-pcp

**Comment by WGandy** [comment]
It looks to me like installing cockpit-pcp triggers the installation of python-pcp. And once I did that, my graphs started working. 
I'm curious about why this package installation is not mentioned in the cockpit install instructions. It seems like a basic functionality that you would expect of cockpit out of the box.

**Comment by LifeTimeCoder** [comment]
Installing python-pcp solved my  issue on Fedora 41 KDE Server

**Comment by connorrichlen** [comment]
**OS: Ubuntu 24.04.1 LTS x86_64
Kernel: 6.8.0-49-generic**

I'm getting no graphs updating whatsoever. APT reports this when attempting to install pcp (my previous package upgrade triggered a removal of cockpit-pcp)


```
$ apt install cockpit-pcp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit-bridge : Conflicts: cockpit-pcp
E: Unable to correct problems, you have held broken packages.
```

Package info offers this:


``` 
$ apt info cockpit-bridge
Package: cockpit-bridge
Version: 329-1~bpo24.04.1
Priority: optional
Section: universe/admin
Source: cockpit
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 851 kB
Provides: cockpit-pcp
Depends: python3:any, glib-networking
Recommends: openssh-client
Suggests: python3-pcp
Conflicts: cockpit-pcp
Breaks: cockpit-ws (<< 181.x)
Replaces: cockpit-dashboard (<< 170.x), cockpit-pcp (<< 236), cockpit-ws (<< 181.x)
Homepage: https://cockpit-project.org/
Download-Size: 378 kB
APT-Manual-Installed: no
APT-Sources: http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages
Description: Cockpit bridge server-side component
 The Cockpit bridge component installed server side and runs commands on
 the system on behalf of the web based user interface.

**Comment by jelly** [comment]
@connorrichlen now you need to install `python3-pcp`

**Comment by connorrichlen** [comment]
Thanks for the reply. I have already done this. See below:

``` 
$ apt install python3-pcp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pcp is already the newest version (6.2.0-1.1build4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by jelly** [comment]
Either way this is a bug, we should be using the internalmetrics, using PCP is more or less aworkaround.

**Comment by martinpitt** [comment]
The internal metrics works by and large:
```
cpf open metrics1 source=internal interval=1000 metrics='[{"name": "network.interface.tx", "derive": "rate"}]' : wait | ssh c cockpit-bridge
```

gives me
```
{
  "source": "internal",
  "interval": 1000,
  "timestamp": 1733826268526.7505,
  "metrics": [
    {
      "name": "network.interface.tx",
      "units": "bytes",
      "instances": [
        "lo",
        "ens14",
        "ens15"
      ],
      "semantics": "counter"
    }
  ]
}

[[[false, false, false]]]
[[[0.0, 498.60284822578484, 0.0]]]
...
```

and it reacts properly to e.g. `ssh c dd of=/dev/null < /dev/zero`. Same for `.rx`.

Comparing to the pcp metrics:
```
cpf open metrics1 source=direct interval=1000 metrics='[{"name": "network.interface.in.bytes", "derive": "rate"}]' : wait | ssh c cockpit-bridge
```
gives me comparable numbers and the same structure as far as I can see:
```
{
  "source": "direct",
  "interval": 1000,
  "timestamp": 1733826377947,
  "metrics": [
    {
      "name": "network.interface.in.bytes",
      "derive": "rate",
      "units": "byte",
      "semantics": "counter",
      "instances": [
        "lo",
        "ens14",
        "ens15"
      ]
    }
  ],
  "now": 1733826377000
}

[[[false, false, false]]]
[[[0.0, 161.4242030378225, 0.0]]]
...
```

So the bridge seems fine, this smells like something on the JS side.

**Comment by martinpitt** [comment]
I'm sorry -- I have wasted two hours on this by now, and I give up. I can't find *any* meaningful difference in the data flow in the maze of UsageMonitor, Metrics_stacked_instances_series cockpit.grid, cockpit.plot, callbacks, event mixins, this weird `transfer()` function, etc. -- this code is so full of indirections, it's absolutely inscrutable for me.

Perhaps @mvollmer has some idea about this? But TBH this all dates back to Peter and Stef.

**Comment by jelly** [comment]
I believe the issue isn't actually in JavaScript but somewhere in our re-implementation of the Python bridge:

The metrics don't seem to arrive connected to the channel it was opened from ie. with the C bridge you get: (with window.debugging = "all")

```
-> recv 6:3!17: [[[null,null,null,407.15420260466635]]]
-> recv 6:3!8: [[[null,null,null,120.40659340657294],[null,null,null,330.45554445311427]]]
```

Python:

```
recv text message: null [[[0.0, 406.30060140082503, 0.0], [0.0, 580.0015956114971, 0.0]]]
```

**Comment by jelly** [comment]
One thing I know I missed when porting is the `now` field in meta which the old bridge did:

```
{"timestamp":1733848925425,"now":1733848925425,"interval":1000,"metrics":[{"name":"network.interface.tx","derive":"rate","instances":["virbr0","enp0s20f0u2u6","lo","enp0s31f6","virbr1","wlp0s20f3"],"units":"bytes","semantics":"counter"}]}45
ch1
[[[false,false,false,false,false,false]]]36
```

Let's add that.

**Comment by jelly** [comment]
Bingo adding `now` back fixes it, that was my fault :(

**Comment by jelly** [comment]
This should be fixed now in https://github.com/cockpit-project/cockpit/pull/21421 and a release is scheduled for next week.

**Comment by philipwmirabelli** [comment]
Nothing really, had the same issue on reinstallation of Ubuntu 24.04.01LTS, had to install the cockpit-pcp package and the graphs both network and RAID disks worked for me.  For good measure I systemctl re-started cockpit.

**Comment by crluehmann** [comment]
Did there end up being a resolution here?  When I try to install cockpit-pcp I get an error:

cockpit-bridge : Conflicts: cockpit-pcp

I'm running Debian on an RPi 5

**Comment by martinpitt** [comment]
@crluehmann Yes, this was fixed in PR #21421 , released in version 331. Indeed cockpit-pcp is no more, you can't install it any more (but that's unrelated, network speed work fine without PCP now)

**Comment by crluehmann** [comment]
Thanks for your response @martinpitt - For what it's worth, network stats have stopped reporting again.  My system noted pcp as not being needed so uninstalled on apt autoremove.  That may or may not be related, but reinstalling cockpit and/or restarting the service doesn't seem to help.

I'm running cockpit 333-1-bpo12+1 on OS: Debian GNU/Linux 12 (bookworm) aarch64; Host: Raspberry Pi 5 Model B Rev 1.0; Kernel: 6.6.74+rpt-rpi-2712

**Comment by martinpitt** [comment]
@crluehmann Dumb question, but let's be sure: Do you actually have cockpit-networkmanager and cockpit-bridge 333 as well, or an older version? It's possible to only update the "cockpit" meta-package. If all packages are at 333, then  I suspect that cockpit tries pcp first, finds it generally available, but then that fails. So if you don't actually care for pcp, I suggest to uninstall all pcp packages and try again?

**Comment by crluehmann** [comment]
@martinpitt thanks for the response.  Reinstalling cockpit, cockpit-networkmanager, and cockpit-bridge have not seemed to help.

cockpit-networkmanager is already the newest version (333-1~bpo12+1).
cockpit-bridge is already the newest version (333-1~bpo12+1).

I do have pcp-conf/stable,now 6.0.3-1.1 arm64 [installed,automatic] -- but no pcp.  Could this be the culprit?  I'm not sure if it has any dependencies.

**Comment by EchedelleLR** [comment]
Uninstalling python3-pcp fixed the issue for me in Debian 12 after installing Cockpit from backports.

Having it installed did not fix anything. In fact, was the cause of the issue x3
