### ISSUE TITLE
Long error messages for domain join flow off the side of the screen, they do not wrap

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#4541]
See https://openqa.stg.fedoraproject.org/tests/21851 - particularly [this screenshot](https://openqa.stg.fedoraproject.org/tests/21851/modules/realmd_join_cockpit_postinstall/steps/29) . When a long error message is shown for a domain join operation, it doesn't wrap as it probably should, it just runs right off the edge of the screen (and causes a bunch of other elements to run off the edge of the screen too). There's probably a 'More' text link at the end which I cannot click because of this, too.

**Comment by dperpeet** [comment]
What's the Cockpit version being used?
The overflow should be fixed at least since https://github.com/cockpit-project/cockpit/commit/381fa711a886f8fb5321dbb28bdb58be06f87378 (0.104)

That said, I get a scrollbar for the long error and that shouldn't happen either.

**Comment by dperpeet** [comment]
Screenshot on current master with a long error message:
![screenshot from 2016-06-08 10-59-15](https://cloud.githubusercontent.com/assets/8711649/15888695/35a7a096-2d68-11e6-8c93-1154a22279af.png)

**Comment by AdamWill** [comment]
Huh. Probably 0.103, because...it seems like new cockpit builds are regularly done for Fedora 24, but no-one has been submitting updates. So Koji has 0.109, but the F24 repos have 0.103, because no-one submitted an update for any of the builds beyond 0.103. Perhaps whoever's doing the cockpit package builds is not aware that Bodhi is in effect for Branched releases?

**Comment by dperpeet** [comment]
Thanks for noticing. We've been having issues that our releases aren't getting enough karma. The 0.109 release is here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-945f8a9ea7
This has enough karma now to move to stable soon. Please update this thread if you still have the issue after upgrading!
I'm leaving this open for now since the style is still broken in master, even if it is more usable now than the version you tested.

**Comment by marusak** [comment]
We how changed this to use alert, but the issue is still there :(
![overflows](https://user-images.githubusercontent.com/12330670/69635486-cbc1e280-1054-11ea-8ec9-d3e1b42d4cc0.png)

**Comment by KKoukiou** [comment]
This is not happening any more.

![Screen Shot 2021-02-12 at 15 49 17](https://user-images.githubusercontent.com/14921356/107782886-e3fd4a80-6d49-11eb-9c99-9c2bc25bd50e.png)
