### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when using ingress on Kubernetes

### ISSUE THREAD

**Issue by aelmehra** [cockpit-project/cockpit#7625]
When creating an Ingress rule for the kubernetes-cockpit service I get ERR_TOO_MANY_REDIRECTS when trying to access the webpage. Here is my configuration:

OS: Centos 7
Kubernetes: v1.7.4
kubernetes-cockpit.json:
{
   "kind":"List",
   "apiVersion":"v1",
   "items":[
      {
         "kind":"ReplicationController",
         "apiVersion":"v1",
         "metadata":{
            "name":"kubernetes-cockpit",
            "labels":{
               "name":"kubernetes-cockpit"
            }
         },
         "spec":{
            "replicas":1,
            "selector":{
               "name":"kubernetes-cockpit"
            },
            "template":{
               "metadata":{
                  "labels":{
                     "name":"kubernetes-cockpit"
                  }
               },
               "spec":{
                  "containers":[{
                    "name": "kubernetes-cockpit",
                    "image": "cockpit/kubernetes:latest",
                    "ports":[{
                        "containerPort":9090,
                        "protocol":"TCP"
                     }],
                    "env":[{
                        "name": "KUBE_INSECURE",
                        "value": "true"
                    }]
                  }]
               }
            }
         }
      },
      {
         "kind":"Service",
         "apiVersion":"v1",
         "metadata":{
            "name":"kubernetes-cockpit",
            "labels":{
               "name":"kubernetes-cockpit"
            }
         },
         "spec":{
             "type": "ClusterIP",
             "ports": [{
                 "protocol": "TCP",
                 "port": 443,
                 "targetPort": 9090
             }],
            "selector":{
               "name":"kubernetes-cockpit"
            }
         }
      }
   ]
}
Ingress:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cockpit-ingress
spec:
  tls:
  - hosts:
    - foo.bar.com
    secretName: foo-secret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-cockpit
          servicePort: 443
        path: /

Any ideas?

**Comment by petervo** [comment]
What urls is it redirecting between? Chances are something need to be corrected with a http -> https redirect.

How did you setup kubernetes? rpms? some other way? Any customized configs?

**Comment by aelmehra** [comment]
When i go to http://foo.bar.com it redirects me too https://foo.bar.com.

I set up kubernetes using kubeadm with no special configs. everything is standard

**Comment by aelmehra** [comment]
the following variables are started with the kube-apiserver:

    - kube-apiserver
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --insecure-port=0
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --allow-privileged=true
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --requestheader-username-headers=X-Remote-User
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --secure-port=6443
    - --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
    - --experimental-bootstrap-token-auth=true
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --requestheader-allowed-names=front-proxy-client
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --authorization-mode=Node,RBAC
    - --advertise-address=10.66.223.62
    - --etcd-servers=http://127.0.0.1:2379
    - --basic-auth-file=/etc/kubernetes/auth.conf

**Comment by petervo** [comment]
Your basic issue is that you are terminating ssl at the ingress, but the cockpit kubernetes container then sees a unencrypted connection and tries to redirect to https. The simpliest fix for now is to run your pod with COCKPIT_KUBE_INSECURE=true and set COCKPIT_KUBE_URL=https://my.url/. You will then probably want to leave your service port on 9090 and set your ingress to refer to that port.

With this the traffic from outside -> ingress will be encrypted but from ingress-> cockpit will be unencrypted. Some kubernetes ingresses only support TLS termination, if that is the case for yours you'll need to use the setup above. 

Others support encrypting the traffic between the ingress and service/pod. In those cases you don't need the the COCKPIT_KUBE_INSECURE but you should have the ingress handle the redirect so only https traffic gets forwarded to the container.

**Comment by aelmehra** [comment]
Thanks for your response.

I've tried updating my configs with your suggestions but I'm still seeing the same redirect error.

`---
kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: kubernetes-cockpit
    labels:
      name: kubernetes-cockpit
  spec:
    replicas: 1
    selector:
      name: kubernetes-cockpit
    template:
      metadata:
        labels:
          name: kubernetes-cockpit
      spec:
        containers:
        - name: kubernetes-cockpit
          image: cockpit/kubernetes:latest
          ports:
          - containerPort: 9090
            protocol: TCP
          env:
          - name: KUBE_INSECURE
            value: 'true'
          - name: COCKPIT_KUBE_URL
            value: 'https://foo.bar.com'
- kind: Service
  apiVersion: v1
  metadata:
    name: kubernetes-cockpit
    labels:
      name: kubernetes-cockpit
  spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
    selector:
      name: kubernetes-cockpit
`

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cockpit-ingress
spec:
  tls:
  - hosts:
    - foo.bar.com
    secretName: secret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-cockpit
          servicePort: 9090
        path: /
`

Am I missing something here?

**Comment by petervo** [comment]
You are still missing COCKPIT_KUBE_INSECURE

**Comment by martinpitt** [comment]
@aelmehra , is this still an issue? Did setting `COCKPIT_KUBE_INSECURE` help?

As this is quite stale, I close this for now. But if it's still an issue, please reopen. Thanks!
